# Generated by Django 5.2.7 on 2025-10-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_beneficiario', models.CharField(max_length=15)),
                ('apellido_beneficiario', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familiar', models.CharField(max_length=15)),
                ('apellido_familiar', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=20)),
                ('presentacion', models.CharField(max_length=10)),
                ('unidad_presentacion', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patologia', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=15)),
                ('apellido_personal', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_calle', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_beneficiario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calle_beneficiario', to='core.beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
                ('tipo_pago', models.CharField(max_length=15)),
                ('numero_referencia', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_beneficiario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_beneficiario', to='core.beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('frecuencia', models.FloatField()),
                ('unidad_frecuencia', models.CharField(max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidado_beneficiario', to='core.beneficiario')),
                ('fk_medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidado_medicamento', to='core.medicamento')),
                ('fk_patologia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidado_patologia', to='core.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_privilegio', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_rol', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilegio_rol', to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_personal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_personal', to='core.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_usuario_rol', to='core.rol')),
                ('fk_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_usuario_usuario', to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fk_usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario_usuario', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Usuario_beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_beneficiario_beneficiario', to='core.beneficiario')),
                ('fk_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_beneficiario_usuario', to='core.usuario')),
            ],
        ),
    ]
