# Generated by Django 5.2.7 on 2025-10-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_beneficiario', models.CharField(max_length=15)),
                ('apellido_beneficiario', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_calle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('frecuencia', models.FloatField()),
                ('unidad_frecuencia', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familiar', models.CharField(max_length=15)),
                ('apellido_familiar', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=20)),
                ('presentacion', models.CharField(max_length=10)),
                ('unidad_presentacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
                ('tipo_pago', models.CharField(max_length=15)),
                ('numero_referencia', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patologia', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=15)),
                ('apellido_personal', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_privilegio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
    ]
