# Generated by Django 5.2.7 on 2025-10-19 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_beneficiciario_calle_cuidado_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidado',
            name='fk_beneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidado_beneficiario', to='core.beneficiario'),
        ),
        migrations.AddField(
            model_name='cuidado',
            name='fk_medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidado_medicamento', to='core.medicamento'),
        ),
        migrations.AddField(
            model_name='cuidado',
            name='fk_patologia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidado_patologia', to='core.patologia'),
        ),
        migrations.AddField(
            model_name='cuidado',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fk_personal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_personal', to='core.personal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
